OCTRI/redcap-report-counts

- js-tests/components/ReportSummary_test.js
- js/components/ConsortReport.vue
- js/components/ReportSummary.vue
- js/services/data-service.js
- lib/data.php
Consolidated all report calls. Updated `ReportSummary` so that it takes a list of report summaries instead of making the report call itself.
> REDDEV-560 summary

- .gitignore
- composer.json
- composer.lock
- js-tests/components/ReportSummary_test.js
- js/components/ConsortReport.vue
- js/components/ReportSummary.vue
- lib/ReportConfigProcessor.php
- lib/ReportStrategy.php
- lib/data.php
- package-lock.json
- package.json
- test_bootstrap.php
- tests/ReportConfigProcessorTest.php
Render itemized counts using the configuration found in `lib/sample.report-config.json`.
> REDDEV-383 itemized counts

- js-tests/components/ReportSummaryForm_test.js
- js/components/ReportSummaryForm.vue
Validate ReportSummaryForm. If there are errors display them and prevent the form from submitting.
> REDDEV-510 form validation

- lib/data.php
I demo'd this work for Liz and she suggested it may be nice to sort the reports by title.
> REDDEV-510 sort reports asc

- lib/ReportConfig.php
I may not get to this tomorrow so feel free to merge if approved. I wanted to see adding an itemized count and did a bit of work in this branch reddev-568-itemized-form and that's when I ran into this bug.
> REDDEV-510 valid fix

- js-tests/components/ConsortReport_test.js
- js-tests/components/ReportSummary_test.js
- js/components/ConsortReport.vue
- js/components/ReportSummary.vue
- js/components/ReportSummaryForm.vue
- js/main.js
- js/services/data-service.js
- lib/ReportConfig.php
- lib/consort-report.css
- lib/settings.php
- tests/ReportConfigTest.php
- webpack.config.js
Each summary can be deleted. UI mimics Vizr styles.
> REDDEV-584 delete summary

- .eslintrc.js
- js-tests/components/ConsortReport_test.js
- js-tests/components/ReportSummaryForm_test.js
- js-tests/components/ReportSummary_test.js
- js/components/ReportSummaryForm.vue
- js/services/data-service.js
- karma.conf.js
- package-lock.json
- package.json
- webpack.config.js
Add ESLint config and plugins needed to lint .vue files.
> Eslint Config

- package-lock.json
- package.json
Update html-webpack-plugin. Fixes an issue where generating `dist/lib/main.php` triggers a rebuild with `webpack --watch`.
> Fix Continuous Rebuild When Watching

- js-tests/components/ConsortReport_test.js
- js-tests/components/ReportSummaryForm_test.js
- js-tests/components/ReportSummary_test.js
- js/components/ConsortReport.vue
- js/components/ReportSummary.vue
- lib/consort-report.css
- package-lock.json
- package.json
This PR includes the drag-and-drop implementation @heathharrelson worked on last week. I picked up the branch and included unit tests for ConsortReport. Submitting PR since Heath is out of office this week.
> REDDEV-590 Re-order summaries

- js-tests/components/ReportSummaryForm_test.js
- js/components/ReportSummaryForm.vue
- lib/consort-report.css
Refactor report summary form so that it matches Vizr's style.
> REDDEV-585 refactored form style

- js/components/ReportSummary.vue
Change the drag handle icon to `fa-arrows-alt`.
> Change Drag Handle Icon

- js-tests/components/ConsortReport_test.js
- js-tests/components/ReportSummaryForm_test.js
- js-tests/components/ReportSummary_test.js
- js/components/ConsortReport.vue
- js/components/ReportSummary.vue
- js/components/ReportSummaryForm.vue
Hide forms on save and cancel.
> REDDEV-594 Hide Form

- js-tests/components/ReportSummaryForm_test.js
- js-tests/report-summary-config_test.js
- js/components/ReportSummaryForm.vue
- js/report-summary-config.js
- lib/consort-report.css
Refactor to display validation feedback next to the invalid fields to make it easier to see what needs to be changed.
> Validation Refactor

- .babelrc
- js/main.js
- karma.conf.js
- package-lock.json
- package.json
- webpack.config.js
Upgrade to the latest version of Babel to match Vizr.
> Upgrade to Babel 7

- js-tests/components/ReportSummary_test.js
- js-tests/report-summary-model_test.js
- js/components/ReportSummary.vue
- js/components/ReportSummaryForm.vue
- js/report-summary-model.js
- lib/SummaryUIProcessor.php
- lib/data.php
- tests/SummaryUIProcessorTest.php
If a report is deleted the body of the card presents a message saying the report does not exist.
> Reddev 591 report changes

- js-tests/components/ReportSummary_test.js
- js/components/ReportSummary.vue
- js/report-summary-model.js
- lib/DataDictionary.php
- lib/SummaryUIProcessor.php
- tests/SummaryUIProcessorTest.php
Display inline error message when missing bucket by field.
Minor test updates:
* replaced double quotes with single quotes
* fixed a few test messages
> REDDEV-609 handle missing bucket by field

- lib/DataDictionary.php
- lib/SummaryUIProcessor.php
- lib/data.php
- tests/SummaryUIProcessorTest.php
Follow up to REDDEV-617.
Moved `getReportFields` logic from `lib/data.php` into `lib/SummaryUIProcessor.php` and unit tested.
> REDDEV-621 refactor

- js-tests/components/ReportSummary_test.js
- js-tests/report-summary-model_test.js
- js/components/ReportSummary.vue
- js/report-summary-model.js
- lib/Database.php
- lib/SummaryUIProcessor.php
- lib/data.php
- lib/settings.php
- tests/SummaryUIProcessorTest.php
Expose report title in each count card.
Add Database class for handling direct SQL calls.
> REDDEV-620 expose report title

- js/components/ReportCountsHelp.vue
Add help text related to user permissions. This is included as a bullet in the existing help text.
> REDDEV-618 add user permission help text

- package-lock.json
- package.json
Update dependencies in response to jQuery CVE.
> CIS-1014 jQuery CVE Updates

- package-lock.json
- package.json
Update webpack and copy-webpack-plugin to patch serialize-javascript XSS vulnerability.
> Updates for CVE-2019-16769

- .github/workflows/test.yml
- package.json
Use GitHub Actions to run JS and PHP unit tests.
> CIS-1224 GitHub CI

- .dependabot/config.yml
Configure Dependabot to update PHP dependencies.
> CIS-1224 Configure Dependabot for PHP

- .dependabot/config.yml
Configure Dependabot to auto-merge safer dependency updates.
> CIS-1224 Configure Dependabot Auto Merge

- .github/workflows/test.yml
- .gitignore
- composer.json
- composer.lock
- tests/ReportConfigTest.php
- tests/SummaryUIProcessorTest.php
Use the latest stable version of PHP and the corresponding PHPUnit for tests. Fixes #69.
> Update to PHP 7.4 and PHPUnit 9

- .github/workflows/test.yml
Run the Webpack build in CI to catch regressions caused by updates.
> Run Webpack in CI

- .github/workflows/test.yml
Use Node.js 14 (latest LTS) to run tests.
> Test With Node 14

- package-lock.json
- package.json
Resolve PostCSS vulnerability related to vue-loader and install missing PostCSS peer dependency.
> PostCSS Updates

- .github/workflows/test.yml
Run tests using the latest Node.js LTS release, 18.x.
> Test With Node 18
